### PR TITLE
update travis to current practices

### PR DESCRIPTION
**Pull request by chippers**
see:
* crate-ci/meta#24
* crate-ci/crate-ci.github.io#14

### CODE REVIEW

**Comment by epage** [comment]
Thanks for doing this!

Not sure why `link.exe` failed on the Windows build.

**Comment by chippers** [comment]
Yeah im looking into fixing this for both repos now.  From what I can guess from the forums so far is that rust knows VS 2013 and 2015, but VS 2017 is used on travis

**Comment by CAD97** [comment]
Travis report that seems relevant: https://travis-ci.community/t/rust-error-could-not-compile-winapi/268

**Comment by chippers** [comment]
yeah thats where i got my sparse info from.  There's not too much info available about the new windows platform since it's been out for less than a day.  ill be keeping an eye out for any new info, but for now this PR and crate-ci/example-bin#1 can just hang open until it's solved.  i suspect there to be fixes to be coming to travis or rust in the following days

**Comment by CAD97** [comment]
Workaround: https://travis-ci.community/t/rust-error-could-not-compile-winapi/268/5

```sh
if [ $TRAVIS_OS_NAME = windows ]; then
  choco install windows-sdk-10.0
fi
```

**Comment by chippers** [comment]
The workaround is a bit ugly but it works.  Hopefully the need for the workaround is removed soon by either the rust team or travis

**Comment by CAD97** [comment]
https://travis-ci.community/t/rust-error-could-not-compile-winapi/268/6?u=cad97

> Hi Everyone
> 
> I changed our image to know include:
> 
> ```
> visualstudio2017buildtools --package-parameters "--allWorkloads --includeRecommended --includeOptional --quiet --norestart --locale en-US --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.ATL --add Microsoft.VisualStudio.Component.VC.ATLMFC"
> visualstudio2017-workload-netcorebuildtools
> visualstudio2017-workload-vctools
> visualstudio2017-workload-webbuildtools
> windows-sdk-10.0
> microsoft-build-tools
> vcredist2017
> ```
> 
> I believe this has fixed the `link.exe` issue.
> 
> These packages might be overkill, all advice welcome.
> 
> Thank you for you help on this \@danreeves and \@SimonSapin

There may now be [disk space issues](https://travis-ci.community/t/rust-error-could-not-compile-winapi/268/7?u=cad97), but the workaround should no longer be necessary.

**Comment by chippers** [comment]
Yeah i just tried with a relatively small crate with `actix-web`, `clap`, and `serde` + a couple of smaller dependencies and it ran out of space.  Now we're waiting for a workaround for the fixed workaround

**Comment by epage** [comment]
Thanks for all the help!

**Pull request merged**
